import "./globals.css";
import "bootstrap-icons/font/bootstrap-icons.css"
import localFont from "next/font/local";
import { Providers } from "./providers";
import AuthProvider from "./AuthProvider";
import { ReduxProvider } from "@/redux/provider";
import { Toaster } from "react-hot-toast";
import { prisma } from "@/libs/prisma";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export async function metadata() {
//   const data = await prisma.app.findUnique({
//       where: {
//           id: 0,
//       },
//       select: {
//           namaapp: true,
//           deskripsi: true,
//           favicon: true,
//       }
//   })

//   return {
//       title: data.namaapp,
//       description: data.deskripsi,
//       icons: {
//           icon: data.favicon !== '' ? data.favicon : '/favicon.ico',
//       },
//   }
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          <AuthProvider>
            <ReduxProvider>
              <Toaster position='top-center' />
              {children}
            </ReduxProvider>
          </AuthProvider>
        </Providers>
      </body>
    </html>
  );
}
